services:
  guacd:
    container_name: guacd
    image: ${IMAGE_GUACD}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - guac-network

  guacamole:
    container_name: guacamole
    depends_on:
      - guacd
      - postgres
    image: ${IMAGE_GUACAMOLE}
    volumes:
      - ./conf/guacamole/server.xml:/usr/local/tomcat/conf/server.xml
# Disable the comment below to enable access to the port
#    ports:
#      - 8080:8080/tcp
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - guac-network

  postgres:
    container_name: postgres
    image: ${IMAGE_POSTGRES}
    restart: unless-stopped
    env_file:
      - .postgres_env
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:Z
# Disable the comment below to enable access to the port
#    ports:
#      - ${PG_PORT}:5432
    networks:
      - guac-network

  nginx:
   container_name: nginx
   restart: unless-stopped
   env_file:
     - .env
   image: ${IMAGE_NGINX}
   volumes:
     - ./nginx/templates:/etc/nginx/templates:ro
     - ./nginx/ssl:/etc/nginx/ssl:ro
     - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
   ports:
     - ${NGX_HTTPS_PORT}:443
   depends_on:
     - guacamole
   networks:
     - guac-network

networks:
  guac-network:
    name: guac-network
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK}